### ISSUE TITLE
Is .data() supported similarly to jQuery?

### ISSUE THREAD

**Issue by klihelp** [kylebarrow/chibi#16]
Is it possible to request/save data to an element?

**Comment by kylebarrow** [comment]
No, I've been using .attr to read/write data values. If you think .data would help though, let me know.

**Comment by klihelp** [comment]
it would be helpful, as you could use simple ```if ( $el.data('example') ) {}``` and set data ```$el.data('example','value')```

**Comment by kylebarrow** [comment]
@klihelp I've added a data method to 3.0.6
