### ISSUE TITLE
Please publish to npm

### ISSUE THREAD

**Issue by van-nguyen** [kylebarrow/chibi#19]
Would be great if we can have this published to npm, so can just have this with npm install. And processed with browserify or webpack.

**Comment by kylebarrow** [comment]
Thanks, I plan to do this but will wait until v3 as this tidies up a lot but also introduces some breaking changes so would prefer to start NPM from this version. v3 should be out soon.

**Comment by derhuerst** [comment]
Why not now? With semver, publishing `3.0.0` won't be hard.

**Comment by kylebarrow** [comment]
Version 3 is released and on npm: npm install chibijs
